### ISSUE TITLE
Scrape bills data from Legistar site

### ISSUE THREAD

**Issue by kfranzen** [openoakland/councilmatic-scraper#5]
Enable the scraper to pull down legislation data by updating the OaklandBillScraper and enabling it at:
https://github.com/openoakland/councilmatic-scraper/blob/dev/oakland/__init__.py#L17

**Comment by georobGWJ** [comment]
I am working on scraping the bills.

**Comment by ekkus93** [comment]
The data is getting stored in the database but it still needs some cleaning up.  Trading  https://github.com/openoakland/councilmatic-scraper/issues/6 with @georobGWJ for this issue.

**Comment by ekkus93** [comment]
Done. I got everything to run clean with an empty database.  Fixed issue with  duplicate actions for:                                         
https://oakland.legistar.com/LegislationDetail.aspx?ID=2907735&GUID=54971489-FEBD-4066-8E6F-524BF00E409A&Options=ID|Text|&Search=Subject%3a%09FY+2017-19+Mayor+And+Council+Budget+Priorities+From%3a%09Office+Of+The+City+Administrator+Recommendation
