### ISSUE TITLE
Scrape City Council voting history from Legistar site

### ISSUE THREAD

**Issue by kfranzen** [openoakland/councilmatic-scraper#6]
Be able to uncomment the vote_events key in init.py and have the OaklandVoteEventScraper scrape votes.

https://github.com/openoakland/councilmatic-scraper/blob/dev/oakland/__init__.py#L18

**Comment by ekkus93** [comment]
Taking this issue. (@kfranzen can you assign this to me?  I don't have permissions to do that.)

**Comment by ekkus93** [comment]
I got some of the bill stuff working.  That needed to be done before voting events.  I'm going to trade this issue with @georobGWJ.

**Comment by ekkus93** [comment]
Done. I got everything to run clean with an empty database.
