### ISSUE TITLE
Scrape events from Legistar

### ISSUE THREAD

**Issue by kfranzen** [openoakland/councilmatic-scraper#8]
Complete the OaklandEventScraper to pull all event and agenda data.

**Comment by kfranzen** [comment]
Doing this work on the events branch.

**Comment by ekkus93** [comment]
Done.  Cleaned up events.py.  Events now have a dependency with bills since some events have bills.  Events are scraped from Jan 1 of last year.  Bills are scraped to from Jan 1 of 2 years back to make sure that all of the bills are available for scraped events.
